from django.urls import path
from . import views

urlpatterns = [
    path("", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("forgot-password/", views.forgot_password_view, name="forgot_password"),
    path("reset-password/", views.reset_password_view, name="reset_password"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("data/", views.data_view, name="data"),
    path("data/table/", views.data_table_view, name="data_table"),
    path("data/download/<str:key>/", views.data_download_view, name="data_download"),
    path("data/import/", views.data_import_view, name="data_import"),
    path("data/scrape/", views.data_scrape_view, name="data_scrape"),
    path("data/scrape/run/", views.scrape_run_view, name="scrape_run"),
    path("data/scrape/stop/", views.scrape_stop_view, name="scrape_stop"),
    path("data/scrape/status/", views.scrape_status_view, name="scrape_status"),
    path("data/scrape/api-keys/", views.api_keys_save_view, name="api_keys_save"),
    path("feedback/", views.feedback_view, name="feedback"),
    path("feedback/submit/", views.survey_submit_view, name="survey_submit"),
    path("about/", views.about_view, name="about"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/change-password/", views.change_password_view, name="change_password"),
    path("accounts/", views.accounts_view, name="accounts"),
    path("accounts/create/", views.account_create_view, name="account_create"),
    path("accounts/<int:pk>/edit/", views.account_edit_view, name="account_edit"),
    path("accounts/<int:pk>/reset-password/", views.account_reset_password_view, name="account_reset_password"),
    path("accounts/<int:pk>/delete/", views.account_delete_view, name="account_delete"),
    path("logout/", views.logout_view, name="logout"),
]